apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uabawbgb3-python 
  janus-idp.io/tekton: uabawbgb3-python
  backstage.io/kubernetes-id: uabawbgb3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uabawbgb3-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  